# Generated by Django 4.2.19 on 2025-02-18 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='create_at',
        ),
    ]
