# Generated by Django 5.1.6 on 2025-02-21 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userprofile_create_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
